### ISSUE TITLE
where to find `tcr_embedding`? Issue with: `import tcr_embedding.utils_preprocessing as utils` 

### ISSUE THREAD

**Issue by yls2g13** [SchubertLab/mvTCR_reproducibility#3]
Thanks for a great package. 
I'm running this notebook from your repo: `preprocessing/10x_preprocessing.ipynb` in an attempt to do the mvTCR tutorial in `[tutorials/03_training_prediction.ipynb](https://github.com/SchubertLab/mvTCR/blob/master/tutorials/03_training_prediction.ipynb)`

I expected to find the module `tcr_embedding` in this repo, but I don't see it anywhere in the code after searching. 
Hope to hear from you!

# code tried:
```
import sys
sys.path.append('/researchers/nicole.saw/util/mvTCR/')
import tcr_embedding.utils_preprocessing as utils
```

# error message:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[46], line 3
      1 import sys
      2 sys.path.append('/researchers/nicole.saw/util/mvTCR/')
----> 3 import tcr_embedding.utils_preprocessing as utils

ModuleNotFoundError: No module named 'tcr_embedding'
```

**Comment by irene-bonapa** [comment]
Hi, thanks for trying out mvTCR! To run the scripts from the reproducibility repo you need to install mvTCR version v0.1.3: `pip install mvtcr==0.1.3`. In newest versions, we have changed 'tcr_embedding' for 'mvTCR', so you can modify `import tcr_embedding.utils_preprocessing as utils` for `import mvtcr.utils_preprocessing as utils`.

However, if your objective is not to directly reproduce the analysis from the publication, but to run the tutorials, you can directly follow the [preprocessing tutorial](https://github.com/SchubertLab/mvTCR/blob/master/tutorials/00_10x_data_preprocessing.ipynb) for 10x from the main repository.
